#!/bin/bash

# Shared Constants

KY_TEMPLATE_ID="0_TEMPLATE"
export KY_TEMPLATE_ID

KY_STRING_DELIMITER=",ky,"
export KY_STRING_DELIMITER

KY_CONTRIBUTORS_ARRAY_DELIMITER=";"
KY_CONTRIBUTORS_USER_DELIMITER=":"
export KY_CONTRIBUTORS_ARRAY_DELIMITER KY_CONTRIBUTORS_USER_DELIMITER

# Org Specific Constants

KY_ORG_ARRAY_KEYS=("styles")
export KY_ORG_ARRAY_KEYS

# Event Specific Constants

KY_EVENT_ARRAY_KEYS=("styles")
export KY_EVENT_ARRAY_KEYS
