#!/bin/bash

# Shared Constants

KY_TEMPLATE_ID="0_TEMPLATE"
export KY_TEMPLATE_ID

SD_LOCALIZATIONS_CSV_REPO_PATH="localization"
SD_REGIONS_CSV_REPO_PATH="localization_regions"
export SD_LOCALIZATIONS_CSV_REPO_PATH SD_REGIONS_CSV_REPO_PATH

KY_STRING_DELIMITER=",ky,"
export KY_STRING_DELIMITER

KY_CONTRIBUTORS_ARRAY_DELIMITER=";"
KY_CONTRIBUTORS_USER_DELIMITER=":"
export KY_CONTRIBUTORS_ARRAY_DELIMITER KY_CONTRIBUTORS_USER_DELIMITER
